// F1 2026 Circuits Data
const circuitsData = [
    {
        name: "Bahrain International Circuit",
        location: "Sakhir, Bahrain",
        length: "5.412 km",
        laps: 57,
        raceDistance: "308.238 km",
        lapRecord: "1:31.447 - Pedro de la Rosa (2005)",
        firstGP: 2004,
        corners: 15,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "320 km/h",
        significance: "Season opener, first Middle Eastern F1 venue, known for dramatic night racing under floodlights and the iconic desert setting. Famous for close racing and multiple DRS zones.",
        characteristics: "High-speed straights, heavy braking zones, abrasive surface causing high tire degradation",
        famousCorner: "Turn 1 - Heavy braking zone, major overtaking opportunity",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Jeddah Corniche Circuit",
        location: "Jeddah, Saudi Arabia",
        length: "6.174 km",
        laps: 50,
        raceDistance: "308.450 km",
        lapRecord: "1:30.734 - Lewis Hamilton (2021)",
        firstGP: 2021,
        corners: 27,
        drsZones: 3,
        circuitType: "Street",
        topSpeed: "340 km/h",
        significance: "Fastest street circuit in F1, stunning Red Sea backdrop, ultra-modern facilities. Known for high-speed walls and spectacular night racing.",
        characteristics: "Extremely fast with average speeds over 250 km/h, narrow walls, challenging for drivers, multiple blind corners",
        famousCorner: "Turn 13 - Flat-out left-hander at 250+ km/h",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Albert Park Circuit",
        location: "Melbourne, Australia",
        length: "5.278 km",
        laps: 58,
        raceDistance: "306.124 km",
        lapRecord: "1:20.235 - Charles Leclerc (2024)",
        firstGP: 1996,
        corners: 14,
        drsZones: 4,
        circuitType: "Semi-Permanent",
        topSpeed: "315 km/h",
        significance: "2026 season opener, beautiful lakeside park setting, passionate Australian fans. Recently modified to improve overtaking opportunities.",
        characteristics: "Semi-street circuit, bumpy surface, mix of high-speed and technical sections, unpredictable weather",
        famousCorner: "Turn 11-12 chicane - Key overtaking spot after modifications",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Suzuka International Racing Course",
        location: "Suzuka, Japan",
        length: "5.807 km",
        laps: 53,
        raceDistance: "307.471 km",
        lapRecord: "1:30.983 - Lewis Hamilton (2019)",
        firstGP: 1987,
        corners: 18,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "320 km/h",
        significance: "One of the most challenging and beloved circuits, unique figure-8 layout, passionate Japanese fans. Tests every aspect of car and driver performance.",
        characteristics: "Figure-8 layout with bridge, flowing high-speed corners, requires perfect rhythm, demanding on tires and brakes",
        famousCorner: "130R - Legendary high-speed left-hander, Spoon Curve, S-Curves",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Japan_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Shanghai International Circuit",
        location: "Shanghai, China",
        length: "5.451 km",
        laps: 56,
        raceDistance: "305.066 km",
        lapRecord: "1:32.238 - Michael Schumacher (2004)",
        firstGP: 2004,
        corners: 16,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "330 km/h",
        significance: "Brought F1 to the massive Chinese market, distinctive architecture, long back straight provides excellent overtaking. Circuit designed by Hermann Tilke.",
        characteristics: "1.2km back straight, unique snail-shaped Turn 1-2 complex, mix of high and low-speed corners",
        famousCorner: "Turns 1-2 - 270-degree decreasing radius corner",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Miami International Autodrome",
        location: "Miami, Florida, USA",
        length: "5.412 km",
        laps: 57,
        raceDistance: "308.326 km",
        lapRecord: "1:29.708 - Max Verstappen (2023)",
        firstGP: 2022,
        corners: 19,
        drsZones: 3,
        circuitType: "Street",
        topSpeed: "320 km/h",
        significance: "Second US race, brings F1 to vibrant Miami, circuit around Hard Rock Stadium. Part of F1's American expansion strategy.",
        characteristics: "Street circuit with high-speed sections, tight corners, marina backdrop, challenging track surface",
        famousCorner: "Turn 17 - Tight hairpin with potential for overtaking",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit Gilles Villeneuve",
        location: "Montreal, Canada",
        length: "4.361 km",
        laps: 70,
        raceDistance: "305.270 km",
        lapRecord: "1:13.078 - Valtteri Bottas (2019)",
        firstGP: 1978,
        corners: 14,
        drsZones: 3,
        circuitType: "Semi-Permanent",
        topSpeed: "335 km/h",
        significance: "Named after legendary Canadian driver, located on Île Notre-Dame, known for unpredictable racing and the 'Wall of Champions'. Passionate Canadian fans create electric atmosphere.",
        characteristics: "Semi-permanent circuit, long straights, heavy braking zones, unforgiving walls, hard on brakes and power units",
        famousCorner: "Wall of Champions (Turn 13-14) - Caught out Schumacher, Hill, Villeneuve in 1999",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit de Monaco",
        location: "Monte Carlo, Monaco",
        length: "3.337 km",
        laps: 78,
        raceDistance: "260.286 km",
        lapRecord: "1:12.909 - Lewis Hamilton (2021)",
        firstGP: 1950,
        corners: 19,
        drsZones: 1,
        circuitType: "Street",
        topSpeed: "290 km/h",
        significance: "The crown jewel of F1, most prestigious race, glamorous setting, part of Triple Crown. Unchanged layout since 1929, ultimate test of precision and concentration.",
        characteristics: "Narrow street circuit, no room for error, overtaking nearly impossible, qualifying crucial, slow speeds but maximum concentration",
        famousCorner: "Casino Square, Fairmont Hairpin (slowest corner in F1), Swimming Pool chicane, Tunnel",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit de Barcelona-Catalunya",
        location: "Barcelona, Spain",
        length: "4.675 km",
        laps: 66,
        raceDistance: "308.424 km",
        lapRecord: "1:18.149 - Max Verstappen (2021)",
        firstGP: 1991,
        corners: 16,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "325 km/h",
        significance: "Primary pre-season testing venue, teams know it intimately, comprehensive test of car performance. Modified in 2023 to improve racing.",
        characteristics: "Mix of high and low-speed corners, long straight, technical final sector, hot temperatures, high tire degradation",
        famousCorner: "Turn 3 - Fast right-hander, Turn 9 - Long right-hander",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Red Bull Ring",
        location: "Spielberg, Austria",
        length: "4.318 km",
        laps: 71,
        raceDistance: "306.452 km",
        lapRecord: "1:05.619 - Carlos Sainz (2020)",
        firstGP: 1970,
        corners: 10,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "315 km/h",
        significance: "Shortest lap on calendar, stunning Alpine setting, home race for Red Bull. Known for close racing and beautiful mountain backdrop.",
        characteristics: "Short lap, only 10 corners, significant elevation changes, high-speed, overtaking opportunities, hard on power units",
        famousCorner: "Turn 3 - Uphill right-hander, Turn 4 - Downhill left",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Austria_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Silverstone Circuit",
        location: "Silverstone, United Kingdom",
        length: "5.891 km",
        laps: 52,
        raceDistance: "306.198 km",
        lapRecord: "1:27.097 - Max Verstappen (2020)",
        firstGP: 1950,
        corners: 18,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "335 km/h",
        significance: "Home of British GP, hosted first ever F1 World Championship race, former RAF airfield. Passionate British fans, high-speed corners test car and driver to the limit.",
        characteristics: "High-speed flowing corners, demands aerodynamic efficiency, unpredictable weather, hard on tires",
        famousCorner: "Copse, Maggotts-Becketts-Chapel complex, Stowe, Club",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit de Spa-Francorchamps",
        location: "Spa, Belgium",
        length: "7.004 km",
        laps: 44,
        raceDistance: "308.052 km",
        lapRecord: "1:46.286 - Valtteri Bottas (2018)",
        firstGP: 1950,
        corners: 19,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "355 km/h",
        significance: "Longest and most challenging circuit, legendary Eau Rouge-Raidillon complex, unpredictable weather. Drivers' favourite, ultimate test of bravery and skill.",
        characteristics: "Massive elevation changes (over 100m), high-speed, unpredictable weather, flowing corners",
        famousCorner: "Eau Rouge-Raidillon - Iconic uphill left-right-left at 300+ km/h, Pouhon, Blanchimont",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Hungaroring",
        location: "Budapest, Hungary",
        length: "4.381 km",
        laps: 70,
        raceDistance: "306.630 km",
        lapRecord: "1:16.627 - Lewis Hamilton (2020)",
        firstGP: 1986,
        corners: 14,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "300 km/h",
        significance: "First F1 race behind Iron Curtain, known as 'Monaco without walls', difficult to overtake. Often produces strategic and unpredictable races.",
        characteristics: "Tight and twisty, low-speed corners, dusty off-line, hot temperatures, qualifying crucial, processional racing",
        famousCorner: "Turn 1 - Downhill right-hander, Turn 2 - Uphill left",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit Zandvoort",
        location: "Zandvoort, Netherlands",
        length: "4.259 km",
        laps: 72,
        raceDistance: "306.587 km",
        lapRecord: "1:11.097 - Lewis Hamilton (2021)",
        firstGP: 1952,
        corners: 14,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "315 km/h",
        significance: "Returned in 2021 after 36-year absence, Max Verstappen's home race, passionate orange-clad Dutch fans. Unique banked corners added for F1 return.",
        characteristics: "Narrow, old-school circuit, banked corners (Turns 3 and 14), challenging to overtake, coastal location, sand can blow onto track",
        famousCorner: "Tarzan (Turn 1) - Banked hairpin, Turn 3 - Banked corner",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Autodromo Nazionale di Monza",
        location: "Monza, Italy",
        length: "5.793 km",
        laps: 53,
        raceDistance: "306.720 km",
        lapRecord: "1:21.046 - Rubens Barrichello (2004)",
        firstGP: 1950,
        corners: 11,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "362 km/h",
        significance: "Temple of Speed, fastest circuit on calendar, passionate Tifosi create incredible atmosphere for Ferrari. Historic venue with rich racing heritage since 1922.",
        characteristics: "Very high-speed, long straights, heavy braking zones, low downforce setup, slipstreaming crucial, hard on engines and brakes",
        famousCorner: "Parabolica - Long fast right-hander, Lesmo corners, Ascari chicane",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuito Urbano de Madrid",
        location: "Madrid, Spain",
        length: "5.474 km",
        laps: 57,
        raceDistance: "312.018 km",
        lapRecord: "TBA — 2026 debut",
        firstGP: 2026,
        corners: 20,
        drsZones: 2,
        circuitType: "Street",
        topSpeed: "310 km/h",
        significance: "Brand new street circuit making its debut in 2026 — Spain's second F1 race. Purpose-built through central Madrid, taking F1 to the heart of one of Europe's great capitals.",
        characteristics: "Brand new layout, tight urban streets, mix of slow technical sections and brief high-speed bursts, heavy braking zones",
        famousCorner: "TBA — first race in 2026 will define the iconic corners",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Baku City Circuit",
        location: "Baku, Azerbaijan",
        length: "6.003 km",
        laps: 51,
        raceDistance: "306.049 km",
        lapRecord: "1:43.009 - Charles Leclerc (2019)",
        firstGP: 2016,
        corners: 20,
        drsZones: 2,
        circuitType: "Street",
        topSpeed: "365 km/h",
        significance: "Longest street circuit, stunning old city backdrop, extremely long straight (2.2km). Known for dramatic races with safety cars and unpredictable outcomes.",
        characteristics: "Narrow castle section, 2.2km straight (fastest point in F1), 90-degree corners, unforgiving walls, high attrition rate",
        famousCorner: "Turn 8 - Narrow castle section, Turn 20 - 90-degree left onto main straight",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Azerbaijan_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Marina Bay Street Circuit",
        location: "Singapore",
        length: "4.940 km",
        laps: 62,
        raceDistance: "306.143 km",
        lapRecord: "1:35.867 - Lewis Hamilton (2023)",
        firstGP: 2008,
        corners: 19,
        drsZones: 3,
        circuitType: "Street",
        topSpeed: "295 km/h",
        significance: "First night race in F1 history, stunning city skyline backdrop, physically demanding in heat and humidity. Iconic event with unique atmosphere.",
        characteristics: "Street circuit, bumpy surface, 90-degree corners, high humidity, physically demanding (2-hour races), safety car likely",
        famousCorner: "Turn 1-2-3 complex, Singapore Sling (Turns 16-17-18)",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Circuit of the Americas",
        location: "Austin, Texas, USA",
        length: "5.513 km",
        laps: 56,
        raceDistance: "308.405 km",
        lapRecord: "1:36.169 - Charles Leclerc (2019)",
        firstGP: 2012,
        corners: 20,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "325 km/h",
        significance: "Purpose-built F1 facility in USA, combines best corners from other circuits, huge American fanbase. Part of F1's successful American expansion.",
        characteristics: "Dramatic uphill Turn 1, mix of high and low-speed corners, long back straight, bumpy surface, inspired by other great circuits",
        famousCorner: "Turn 1 - Steep uphill left-hander, Turns 3-6 - Maggotts-Becketts inspired, Turns 12-15 - Stadium section",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Autódromo Hermanos Rodríguez",
        location: "Mexico City, Mexico",
        length: "4.304 km",
        laps: 71,
        raceDistance: "305.354 km",
        lapRecord: "1:17.774 - Valtteri Bottas (2021)",
        firstGP: 1963,
        corners: 17,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "345 km/h",
        significance: "High altitude (2,285m) affects engine performance and aerodynamics, passionate Mexican fans, named after Rodriguez brothers. Unique challenges due to thin air.",
        characteristics: "High altitude reduces downforce and power, long straight, stadium section, thin air affects cooling, unique challenge for teams",
        famousCorner: "Peraltada - Long fast right-hander, Esses (Turns 1-3), Stadium section",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Autódromo José Carlos Pace (Interlagos)",
        location: "São Paulo, Brazil",
        length: "4.309 km",
        laps: 71,
        raceDistance: "305.879 km",
        lapRecord: "1:10.540 - Valtteri Bottas (2018)",
        firstGP: 1973,
        corners: 15,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "325 km/h",
        significance: "Anti-clockwise layout, passionate Brazilian fans, often produces dramatic championship deciders. Named after Brazilian F1 driver José Carlos Pace.",
        characteristics: "Anti-clockwise, bumpy surface, elevation changes, unpredictable weather, challenging Senna S, great overtaking opportunities",
        famousCorner: "Senna S (Turns 1-2), Descida do Lago (Turn 12), Juncao (Turn 10)",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Las Vegas Street Circuit",
        location: "Las Vegas, Nevada, USA",
        length: "6.120 km",
        laps: 50,
        raceDistance: "305.880 km",
        lapRecord: "1:35.490 - Oscar Piastri (2023)",
        firstGP: 2023,
        corners: 17,
        drsZones: 2,
        circuitType: "Street",
        topSpeed: "350 km/h",
        significance: "Saturday night race on the famous Las Vegas Strip, spectacular setting with casinos and lights. Major event for F1's American growth, high-speed street circuit.",
        characteristics: "Very high-speed street circuit, long straights, cold temperatures, runs past famous landmarks, low-downforce setup",
        famousCorner: "Turn 1 - High-speed right after long straight, Turns along the Strip",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Lusail International Circuit",
        location: "Lusail, Qatar",
        length: "5.380 km",
        laps: 57,
        raceDistance: "308.611 km",
        lapRecord: "1:24.319 - Max Verstappen (2023)",
        firstGP: 2021,
        corners: 16,
        drsZones: 2,
        circuitType: "Permanent",
        topSpeed: "320 km/h",
        significance: "Joined calendar in 2021, modern facility, night race under floodlights. Built for MotoGP, adapted for F1, long-term deal through 2032.",
        characteristics: "Fast and flowing, multiple high-speed corners, good overtaking opportunities, night race, desert setting",
        famousCorner: "Turn 1 - Fast left-hander, Turn 6 - Long right-hander",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Qatar_Circuit.png.transform/9col/image.png"
    },
    {
        name: "Yas Marina Circuit",
        location: "Abu Dhabi, UAE",
        length: "5.281 km",
        laps: 58,
        raceDistance: "306.183 km",
        lapRecord: "1:26.103 - Max Verstappen (2021)",
        firstGP: 2009,
        corners: 16,
        drsZones: 3,
        circuitType: "Permanent",
        topSpeed: "330 km/h",
        significance: "Season finale, twilight race (starts in daylight, finishes under lights), iconic Yas Hotel. Scene of controversial 2021 championship decider. Modified in 2021 to improve racing.",
        characteristics: "Twilight race, mix of high and low-speed sections, marina backdrop, modified in 2021 for better racing",
        famousCorner: "Turn 9 - Hairpin under Yas Hotel, Turns 5-6 - Fast chicane",
        layoutImage: "https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png.transform/9col/image.png"
    }
];
