// Comprehensive F1 Quiz Questions Database
const quizData = [
    // Driver History & Championships
    { question: "Who won the first ever Formula 1 World Championship in 1950?", options: ["Giuseppe Farina", "Juan Manuel Fangio", "Alberto Ascari", "Stirling Moss"], answer: "Giuseppe Farina" },
    { question: "How many World Championships did Michael Schumacher win?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "How many World Championships has Lewis Hamilton won?", options: ["6", "7", "8", "9"], answer: "7" },
    { question: "Which driver won 4 consecutive championships from 2010-2013?", options: ["Sebastian Vettel", "Lewis Hamilton", "Fernando Alonso", "Jenson Button"], answer: "Sebastian Vettel" },
    { question: "Who is the youngest F1 World Champion ever?", options: ["Max Verstappen", "Sebastian Vettel", "Lewis Hamilton", "Fernando Alonso"], answer: "Sebastian Vettel" },
    { question: "Which driver has the most race wins in F1 history?", options: ["Michael Schumacher", "Lewis Hamilton", "Sebastian Vettel", "Ayrton Senna"], answer: "Lewis Hamilton" },
    { question: "Who won the 2009 F1 World Championship?", options: ["Jenson Button", "Sebastian Vettel", "Lewis Hamilton", "Rubens Barrichello"], answer: "Jenson Button" },
    { question: "Which driver won back-to-back championships in 2005 and 2006?", options: ["Fernando Alonso", "Michael Schumacher", "Kimi Räikkönen", "Felipe Massa"], answer: "Fernando Alonso" },
    { question: "Who was the 2007 F1 World Champion?", options: ["Kimi Räikkönen", "Lewis Hamilton", "Fernando Alonso", "Felipe Massa"], answer: "Kimi Räikkönen" },
    { question: "Which driver won the championship by just one point in 2008?", options: ["Lewis Hamilton", "Felipe Massa", "Kimi Räikkönen", "Robert Kubica"], answer: "Lewis Hamilton" },
    
    // Teams & Constructors
    { question: "Which team has won the most Constructors' Championships?", options: ["Ferrari", "McLaren", "Williams", "Mercedes"], answer: "Ferrari" },
    { question: "In which year did Mercedes return to F1 as a constructor?", options: ["2008", "2009", "2010", "2011"], answer: "2010" },
    { question: "Which team won 8 consecutive Constructors' Championships from 2014-2021?", options: ["Mercedes", "Red Bull", "Ferrari", "McLaren"], answer: "Mercedes" },
    { question: "What was Red Bull Racing originally called?", options: ["Jaguar Racing", "Stewart Grand Prix", "Minardi", "Jordan"], answer: "Jaguar Racing" },
    { question: "Which team is based in Maranello, Italy?", options: ["Ferrari", "AlphaTauri", "Alfa Romeo", "Maserati"], answer: "Ferrari" },
    { question: "What is McLaren's home base?", options: ["Woking, UK", "Oxford, UK", "Milton Keynes, UK", "Brackley, UK"], answer: "Woking, UK" },
    { question: "Which team did Lewis Hamilton drive for before Mercedes?", options: ["McLaren", "Ferrari", "Red Bull", "Renault"], answer: "McLaren" },
    { question: "What color is traditionally associated with Ferrari?", options: ["Rosso Corsa (Red)", "British Racing Green", "Silver", "Blue"], answer: "Rosso Corsa (Red)" },
    { question: "Which team is owned by Lawrence Stroll?", options: ["Aston Martin", "Williams", "Alpine", "Haas"], answer: "Aston Martin" },
    { question: "What was the Aston Martin team called before 2021?", options: ["Racing Point", "Force India", "Jordan", "Spyker"], answer: "Racing Point" },
    
    // Circuits & Races
    { question: "Which circuit is known as the 'Temple of Speed'?", options: ["Monza", "Spa-Francorchamps", "Silverstone", "Suzuka"], answer: "Monza" },
    { question: "What is the longest circuit on the F1 calendar?", options: ["Spa-Francorchamps", "Silverstone", "Suzuka", "Circuit of the Americas"], answer: "Spa-Francorchamps" },
    { question: "Which circuit features the famous 'Eau Rouge' corner?", options: ["Spa-Francorchamps", "Monza", "Silverstone", "Monaco"], answer: "Spa-Francorchamps" },
    { question: "What is the shortest circuit on the F1 calendar?", options: ["Monaco", "Zandvoort", "Red Bull Ring", "Hungaroring"], answer: "Monaco" },
    { question: "Which circuit is known as the 'Cathedral of Speed'?", options: ["Monza", "Spa", "Silverstone", "Suzuka"], answer: "Monza" },
    { question: "In which country is the Circuit de Barcelona-Catalunya?", options: ["Spain", "Portugal", "Italy", "France"], answer: "Spain" },
    { question: "Which circuit hosted the first ever F1 race in 1950?", options: ["Silverstone", "Monaco", "Monza", "Spa"], answer: "Silverstone" },
    { question: "What is the home race for Mercedes?", options: ["German Grand Prix", "Austrian Grand Prix", "British Grand Prix", "Belgian Grand Prix"], answer: "German Grand Prix" },
    { question: "Which circuit is located in Suzuka, Japan?", options: ["Suzuka Circuit", "Fuji Speedway", "Twin Ring Motegi", "Okayama Circuit"], answer: "Suzuka Circuit" },
    { question: "What is the Italian Grand Prix circuit?", options: ["Monza", "Imola", "Mugello", "Misano"], answer: "Monza" },
    
    // Technical & Rules
    { question: "What does DRS stand for?", options: ["Drag Reduction System", "Direct Racing System", "Drive Reduction Speed", "Dynamic Race System"], answer: "Drag Reduction System" },
    { question: "How many points does the race winner receive?", options: ["25", "20", "15", "30"], answer: "25" },
    { question: "What is the minimum weight of an F1 car (including driver)?", options: ["798 kg", "750 kg", "800 kg", "850 kg"], answer: "798 kg" },
    { question: "How many power units can a driver use per season without penalty?", options: ["3", "2", "4", "5"], answer: "3" },
    { question: "What does the black flag with an orange circle mean?", options: ["Mechanical problem", "Disqualification", "Slow down", "Pit stop required"], answer: "Mechanical problem" },
    { question: "How many gears do modern F1 cars have?", options: ["8", "7", "6", "9"], answer: "8" },
    { question: "What is the maximum fuel capacity of an F1 car?", options: ["110 kg", "100 kg", "120 kg", "105 kg"], answer: "110 kg" },
    { question: "What does ERS stand for?", options: ["Energy Recovery System", "Electric Racing System", "Engine Reduction System", "Enhanced Race Speed"], answer: "Energy Recovery System" },
    { question: "How many practice sessions are there in a typical race weekend?", options: ["3", "2", "4", "1"], answer: "3" },
    { question: "What is the penalty for causing a collision?", options: ["Time penalty or grid drop", "Disqualification", "Fine only", "Warning"], answer: "Time penalty or grid drop" },
    
    // Famous Moments & Records
    { question: "Who holds the record for most pole positions?", options: ["Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Sebastian Vettel"], answer: "Lewis Hamilton" },
    { question: "Which driver won from 14th on the grid at Monza 2008?", options: ["Sebastian Vettel", "Lewis Hamilton", "Fernando Alonso", "Kimi Räikkönen"], answer: "Sebastian Vettel" },
    { question: "Who won the 2021 F1 World Championship?", options: ["Max Verstappen", "Lewis Hamilton", "Sergio Perez", "Valtteri Bottas"], answer: "Max Verstappen" },
    { question: "Which driver survived a horrific crash at Bahrain 2020?", options: ["Romain Grosjean", "Lance Stroll", "Kevin Magnussen", "Antonio Giovinazzi"], answer: "Romain Grosjean" },
    { question: "Who won the chaotic 2020 Italian Grand Prix?", options: ["Pierre Gasly", "Carlos Sainz", "Lance Stroll", "Lando Norris"], answer: "Pierre Gasly" },
    { question: "Which driver has the most fastest laps?", options: ["Lewis Hamilton", "Michael Schumacher", "Kimi Räikkönen", "Max Verstappen"], answer: "Lewis Hamilton" },
    { question: "Who won the 2012 championship in the final race?", options: ["Sebastian Vettel", "Fernando Alonso", "Kimi Räikkönen", "Lewis Hamilton"], answer: "Sebastian Vettel" },
    { question: "Which driver won their home race in 2021 at Zandvoort?", options: ["Max Verstappen", "Lewis Hamilton", "George Russell", "Lando Norris"], answer: "Max Verstappen" },
    { question: "Who was the last driver to win a race for Williams?", options: ["Pastor Maldonado", "Felipe Massa", "Valtteri Bottas", "Juan Pablo Montoya"], answer: "Pastor Maldonado" },
    { question: "Which driver won the 2022 F1 World Championship?", options: ["Max Verstappen", "Charles Leclerc", "Sergio Perez", "George Russell"], answer: "Max Verstappen" },
    
    // Driver Nationalities & Numbers
    { question: "What is Max Verstappen's racing number?", options: ["1", "33", "3", "11"], answer: "1" },
    { question: "What is Lewis Hamilton's racing number?", options: ["44", "1", "4", "14"], answer: "44" },
    { question: "Which country is Charles Leclerc from?", options: ["Monaco", "France", "Italy", "Belgium"], answer: "Monaco" },
    { question: "What is Fernando Alonso's racing number?", options: ["14", "5", "1", "2"], answer: "14" },
    { question: "Which country is Sergio Perez from?", options: ["Mexico", "Spain", "Brazil", "Colombia"], answer: "Mexico" },
    { question: "What is Lando Norris's racing number?", options: ["4", "14", "44", "40"], answer: "4" },
    { question: "Which country is George Russell from?", options: ["United Kingdom", "Australia", "Canada", "New Zealand"], answer: "United Kingdom" },
    { question: "What is Carlos Sainz Jr.'s racing number?", options: ["55", "5", "15", "50"], answer: "55" },
    { question: "Which country is Yuki Tsunoda from?", options: ["Japan", "China", "South Korea", "Thailand"], answer: "Japan" },
    { question: "What is Oscar Piastri's racing number?", options: ["81", "18", "8", "1"], answer: "81" },

    // Legendary Drivers
    { question: "In which year did Ayrton Senna tragically die?", options: ["1994", "1993", "1995", "1992"], answer: "1994" },
    { question: "How many championships did Ayrton Senna win?", options: ["3", "2", "4", "5"], answer: "3" },
    { question: "Which team did Ayrton Senna drive for when he died?", options: ["Williams", "McLaren", "Lotus", "Ferrari"], answer: "Williams" },
    { question: "Who was Ayrton Senna's biggest rival?", options: ["Alain Prost", "Nigel Mansell", "Nelson Piquet", "Michael Schumacher"], answer: "Alain Prost" },
    { question: "How many championships did Alain Prost win?", options: ["4", "3", "5", "2"], answer: "4" },
    { question: "Which driver is known as 'The Professor'?", options: ["Alain Prost", "Niki Lauda", "Jackie Stewart", "Jim Clark"], answer: "Alain Prost" },
    { question: "How many times did Juan Manuel Fangio win the championship?", options: ["5", "4", "6", "3"], answer: "5" },
    { question: "Which driver survived a horrific crash and fire at the 1976 German GP?", options: ["Niki Lauda", "James Hunt", "Clay Regazzoni", "Jochen Mass"], answer: "Niki Lauda" },
    { question: "Who won the 1976 F1 World Championship?", options: ["James Hunt", "Niki Lauda", "Jody Scheckter", "Mario Andretti"], answer: "James Hunt" },
    { question: "Which driver is known as 'The Flying Finn'?", options: ["Mika Häkkinen", "Kimi Räikkönen", "Valtteri Bottas", "Heikki Kovalainen"], answer: "Mika Häkkinen" },
    
    // Team Principals & Personalities
    { question: "Who is the current Team Principal of Ferrari?", options: ["Frédéric Vasseur", "Mattia Binotto", "Maurizio Arrivabene", "Jean Todt"], answer: "Frédéric Vasseur" },
    { question: "Who is the Team Principal of Red Bull Racing?", options: ["Christian Horner", "Helmut Marko", "Adrian Newey", "Franz Tost"], answer: "Christian Horner" },
    { question: "Who is the Team Principal of Mercedes?", options: ["Toto Wolff", "Niki Lauda", "Ross Brawn", "Norbert Haug"], answer: "Toto Wolff" },
    { question: "Who is Red Bull's Chief Technical Officer?", options: ["Adrian Newey", "Christian Horner", "Pierre Waché", "Paul Monaghan"], answer: "Adrian Newey" },
    { question: "Who is the Team Principal of McLaren?", options: ["Andrea Stella", "Zak Brown", "Andreas Seidl", "Martin Whitmarsh"], answer: "Andrea Stella" },
    { question: "Who is the CEO of McLaren Racing?", options: ["Zak Brown", "Andrea Stella", "Ron Dennis", "Martin Whitmarsh"], answer: "Zak Brown" },
    { question: "Who was Ferrari's most successful Team Principal?", options: ["Jean Todt", "Enzo Ferrari", "Mattia Binotto", "Stefano Domenicali"], answer: "Jean Todt" },
    { question: "Who is the Team Principal of Aston Martin?", options: ["Mike Krack", "Otmar Szafnauer", "Martin Whitmarsh", "Eric Boullier"], answer: "Mike Krack" },
    { question: "Who owns the Aston Martin F1 team?", options: ["Lawrence Stroll", "Mike Krack", "Fernando Alonso", "Sebastian Vettel"], answer: "Lawrence Stroll" },
    { question: "Who is the Team Principal of Alpine?", options: ["Bruno Famin", "Otmar Szafnauer", "Cyril Abiteboul", "Flavio Briatore"], answer: "Bruno Famin" },
    
    // Circuits - Detailed
    { question: "How many corners does the Monaco circuit have?", options: ["19", "17", "21", "15"], answer: "19" },
    { question: "What is the famous corner at Silverstone called?", options: ["Copse", "Maggotts", "Stowe", "Abbey"], answer: "Copse" },
    { question: "Which circuit features the 'Parabolica' corner?", options: ["Monza", "Imola", "Mugello", "Spa"], answer: "Monza" },
    { question: "What is the famous corner sequence at Suzuka?", options: ["S Curves", "Esses", "Chicane", "Hairpin"], answer: "S Curves" },
    { question: "Which circuit has the 'Casino Square'?", options: ["Monaco", "Singapore", "Abu Dhabi", "Baku"], answer: "Monaco" },
    { question: "What is the elevation change at Spa-Francorchamps?", options: ["Over 100m", "50m", "75m", "150m"], answer: "Over 100m" },
    { question: "Which circuit is known for the 'Corkscrew'?", options: ["Laguna Seca (not F1)", "COTA", "Interlagos", "Suzuka"], answer: "Laguna Seca (not F1)" },
    { question: "What is the famous hairpin at Monaco called?", options: ["Fairmont Hairpin", "Loews Hairpin", "Casino Hairpin", "Portier"], answer: "Fairmont Hairpin" },
    { question: "Which circuit features 'Turn 8' known as the best overtaking spot?", options: ["Baku", "Singapore", "Monaco", "Abu Dhabi"], answer: "Baku" },
    { question: "What is the length of the Monaco circuit?", options: ["3.337 km", "4.5 km", "5.8 km", "2.9 km"], answer: "3.337 km" },
    
    // Race Strategy & Pit Stops
    { question: "What is the minimum time for a pit stop?", options: ["Around 2 seconds", "5 seconds", "1 second", "3 seconds"], answer: "Around 2 seconds" },
    { question: "How many tire compounds does Pirelli bring to each race?", options: ["3", "2", "4", "5"], answer: "3" },
    { question: "What color stripe indicates the soft tire compound?", options: ["Red", "Yellow", "White", "Green"], answer: "Red" },
    { question: "What color stripe indicates the medium tire compound?", options: ["Yellow", "Red", "White", "Green"], answer: "Yellow" },
    { question: "What color stripe indicates the hard tire compound?", options: ["White", "Red", "Yellow", "Blue"], answer: "White" },
    { question: "What is the wet weather tire called?", options: ["Intermediate", "Full Wet", "Rain", "Monsoon"], answer: "Intermediate" },
    { question: "What color are the full wet tires?", options: ["Blue", "Green", "Red", "Orange"], answer: "Blue" },
    { question: "How many mechanics are allowed to work on a car during a pit stop?", options: ["Unlimited", "12", "15", "20"], answer: "Unlimited" },
    { question: "What is undercut in F1 strategy?", options: ["Pitting before your rival", "Pitting after your rival", "Staying out longer", "Two-stop strategy"], answer: "Pitting before your rival" },
    { question: "What is overcut in F1 strategy?", options: ["Staying out longer than rival", "Pitting before rival", "Two-stop strategy", "No-stop strategy"], answer: "Staying out longer than rival" },
    
    // Modern Era (2014-Present)
    { question: "Which team dominated the hybrid era from 2014?", options: ["Mercedes", "Red Bull", "Ferrari", "McLaren"], answer: "Mercedes" },
    { question: "Who won the 2014 F1 World Championship?", options: ["Lewis Hamilton", "Nico Rosberg", "Sebastian Vettel", "Daniel Ricciardo"], answer: "Lewis Hamilton" },
    { question: "Who won the 2016 F1 World Championship?", options: ["Nico Rosberg", "Lewis Hamilton", "Sebastian Vettel", "Max Verstappen"], answer: "Nico Rosberg" },
    { question: "Which driver retired immediately after winning the 2016 championship?", options: ["Nico Rosberg", "Jenson Button", "Felipe Massa", "Kimi Räikkönen"], answer: "Nico Rosberg" },
    { question: "Who won the 2020 Turkish Grand Prix from 6th on the grid?", options: ["Lewis Hamilton", "Sergio Perez", "Sebastian Vettel", "Max Verstappen"], answer: "Lewis Hamilton" },
    { question: "Which race did George Russell almost win for Williams in 2020?", options: ["Sakhir GP", "Turkish GP", "Italian GP", "Belgian GP"], answer: "Sakhir GP" },
    { question: "Who won the 2021 Saudi Arabian Grand Prix?", options: ["Lewis Hamilton", "Max Verstappen", "Valtteri Bottas", "Sergio Perez"], answer: "Lewis Hamilton" },
    { question: "What was controversial about the 2021 Abu Dhabi GP?", options: ["Safety car restart", "Red flag", "Penalty decision", "Weather conditions"], answer: "Safety car restart" },
    { question: "Who won the 2023 F1 World Championship?", options: ["Max Verstappen", "Sergio Perez", "Lewis Hamilton", "Fernando Alonso"], answer: "Max Verstappen" },
    { question: "How many races did Max Verstappen win in 2023?", options: ["19", "15", "21", "17"], answer: "19" },
    
    // Rookies & Young Drivers
    { question: "Who is the youngest driver to start an F1 race?", options: ["Max Verstappen", "Lance Stroll", "Lando Norris", "Sebastian Vettel"], answer: "Max Verstappen" },
    { question: "How old was Max Verstappen when he made his F1 debut?", options: ["17", "18", "16", "19"], answer: "17" },
    { question: "Which team did Max Verstappen debut with?", options: ["Toro Rosso", "Red Bull", "Sauber", "Williams"], answer: "Toro Rosso" },
    { question: "Who won Rookie of the Year in 2019?", options: ["Lando Norris", "Alexander Albon", "George Russell", "Antonio Giovinazzi"], answer: "Lando Norris" },
    { question: "Which driver moved from Williams to Mercedes in 2022?", options: ["George Russell", "Valtteri Bottas", "Nicholas Latifi", "Alex Albon"], answer: "George Russell" },
    { question: "Who replaced Sebastian Vettel at Aston Martin in 2023?", options: ["Fernando Alonso", "Oscar Piastri", "Nyck de Vries", "Logan Sargeant"], answer: "Fernando Alonso" },
    { question: "Which rookie joined McLaren in 2023?", options: ["Oscar Piastri", "Logan Sargeant", "Nyck de Vries", "Liam Lawson"], answer: "Oscar Piastri" },
    { question: "Who is the first American F1 driver since 2015?", options: ["Logan Sargeant", "Colton Herta", "Alexander Rossi", "Scott Speed"], answer: "Logan Sargeant" },
    { question: "Which team did Oscar Piastri have a contract dispute with?", options: ["Alpine", "McLaren", "Williams", "Aston Martin"], answer: "Alpine" },
    { question: "Who replaced Daniel Ricciardo at McLaren in 2023?", options: ["Oscar Piastri", "Lando Norris", "Nyck de Vries", "Alex Albon"], answer: "Oscar Piastri" },
    
    // Qualifying & Sprint Races
    { question: "How many parts are there in qualifying?", options: ["3", "2", "4", "1"], answer: "3" },
    { question: "How many drivers are eliminated in Q1?", options: ["5", "6", "4", "7"], answer: "5" },
    { question: "How many drivers are eliminated in Q2?", options: ["5", "6", "4", "7"], answer: "5" },
    { question: "How many drivers compete in Q3?", options: ["10", "8", "12", "6"], answer: "10" },
    { question: "How many points does the sprint race winner get?", options: ["8", "10", "15", "25"], answer: "8" },
    { question: "How many laps is a typical sprint race?", options: ["Around 100km", "50km", "150km", "200km"], answer: "Around 100km" },
    { question: "When was the sprint race format introduced?", options: ["2021", "2020", "2022", "2019"], answer: "2021" },
    { question: "Which circuit hosted the first sprint race?", options: ["Silverstone", "Monza", "Interlagos", "Spa"], answer: "Silverstone" },
    { question: "Do drivers get points for fastest lap in sprint races?", options: ["No", "Yes", "Only top 3", "Only winner"], answer: "No" },
    { question: "What determines the grid for the sprint race?", options: ["Sprint Qualifying", "Friday Qualifying", "Practice times", "Championship order"], answer: "Sprint Qualifying" },
    
    // Penalties & Flags
    { question: "What does a blue flag mean?", options: ["Let faster car pass", "Danger ahead", "Slow down", "Pit stop required"], answer: "Let faster car pass" },
    { question: "What does a yellow flag mean?", options: ["Danger, slow down", "Race stopped", "Last lap", "Pit lane open"], answer: "Danger, slow down" },
    { question: "What does a red flag mean?", options: ["Session stopped", "Disqualification", "Penalty", "Danger ahead"], answer: "Session stopped" },
    { question: "What does a black and white flag mean?", options: ["Warning for unsportsmanlike behavior", "Disqualification", "Mechanical issue", "Slow down"], answer: "Warning for unsportsmanlike behavior" },
    { question: "What does a chequered flag mean?", options: ["Race finished", "Last lap", "Pit stop", "Caution"], answer: "Race finished" },
    { question: "What is a 5-second time penalty usually for?", options: ["Minor infringement", "Causing collision", "Speeding in pit lane", "Ignoring blue flags"], answer: "Minor infringement" },
    { question: "What is a 10-second time penalty usually for?", options: ["More serious infringement", "Minor infringement", "Speeding", "Track limits"], answer: "More serious infringement" },
    { question: "What is the penalty for speeding in the pit lane?", options: ["Time penalty or fine", "Disqualification", "Grid drop", "Warning"], answer: "Time penalty or fine" },
    { question: "What happens if you ignore blue flags?", options: ["Time penalty", "Black flag", "Warning", "Grid penalty"], answer: "Time penalty" },
    { question: "What is a drive-through penalty?", options: ["Drive through pit lane without stopping", "10-second stop", "5-second stop", "Grid penalty"], answer: "Drive through pit lane without stopping" },

    // Car Components & Technology
    { question: "What is the halo device designed to protect?", options: ["Driver's head", "Engine", "Wheels", "Fuel tank"], answer: "Driver's head" },
    { question: "In which year was the halo introduced?", options: ["2018", "2017", "2019", "2016"], answer: "2018" },
    { question: "What does MGU-K stand for?", options: ["Motor Generator Unit - Kinetic", "Motor Gear Unit - Kinetic", "Main Generator Unit - Kinetic", "Motor Generator Unit - Kinematic"], answer: "Motor Generator Unit - Kinetic" },
    { question: "What does MGU-H stand for?", options: ["Motor Generator Unit - Heat", "Motor Gear Unit - Heat", "Main Generator Unit - Heat", "Motor Generator Unit - Hybrid"], answer: "Motor Generator Unit - Heat" },
    { question: "What is the V-angle of current F1 engines?", options: ["90 degrees", "60 degrees", "120 degrees", "180 degrees"], answer: "90 degrees" },
    { question: "How many cylinders do current F1 engines have?", options: ["6", "8", "4", "10"], answer: "6" },
    { question: "What is the engine capacity of current F1 cars?", options: ["1.6L", "2.4L", "3.0L", "1.8L"], answer: "1.6L" },
    { question: "What is the maximum RPM of current F1 engines?", options: ["15,000", "18,000", "12,000", "20,000"], answer: "15,000" },
    { question: "What material are F1 brake discs made from?", options: ["Carbon fiber", "Steel", "Ceramic", "Aluminum"], answer: "Carbon fiber" },
    { question: "What is the typical operating temperature of F1 brakes?", options: ["1000°C", "500°C", "750°C", "1500°C"], answer: "1000°C" },
    
    // Historic Races & Moments
    { question: "Which race is known as the 'Race of Champions'?", options: ["Monaco GP", "British GP", "Italian GP", "Belgian GP"], answer: "Monaco GP" },
    { question: "What year did F1 introduce the safety car?", options: ["1993", "1990", "1995", "1988"], answer: "1993" },
    { question: "Who was the first F1 safety car driver?", options: ["Max Angelelli", "Bernd Mayländer", "Bruno Correia", "Olivier Gendebien"], answer: "Max Angelelli" },
    { question: "Who is the current F1 safety car driver?", options: ["Bernd Mayländer", "Bruno Correia", "Max Angelelli", "Alan van der Merwe"], answer: "Bernd Mayländer" },
    { question: "What car is used as the F1 safety car?", options: ["Mercedes-AMG GT", "Aston Martin Vantage", "BMW M5", "Porsche 911"], answer: "Mercedes-AMG GT" },
    { question: "What year was the first F1 World Championship?", options: ["1950", "1946", "1955", "1960"], answer: "1950" },
    { question: "Which circuit hosted the first night race?", options: ["Singapore", "Abu Dhabi", "Bahrain", "Qatar"], answer: "Singapore" },
    { question: "What year was the first Singapore night race?", options: ["2008", "2007", "2009", "2010"], answer: "2008" },
    { question: "Which driver won the first Singapore GP?", options: ["Fernando Alonso", "Lewis Hamilton", "Felipe Massa", "Kimi Räikkönen"], answer: "Fernando Alonso" },
    { question: "What was controversial about the 2008 Singapore GP?", options: ["Crashgate scandal", "Safety car timing", "Fuel irregularity", "Track limits"], answer: "Crashgate scandal" },
    
    // Specific Grand Prix
    { question: "Which Grand Prix is held at Yas Marina Circuit?", options: ["Abu Dhabi", "Bahrain", "Saudi Arabia", "Qatar"], answer: "Abu Dhabi" },
    { question: "Which Grand Prix is held at Circuit Gilles Villeneuve?", options: ["Canadian", "French", "Belgian", "Swiss"], answer: "Canadian" },
    { question: "Which Grand Prix is held at Autodromo Hermanos Rodriguez?", options: ["Mexican", "Brazilian", "Argentine", "Chilean"], answer: "Mexican" },
    { question: "Which Grand Prix is held at Interlagos?", options: ["Brazilian", "Argentine", "Mexican", "Colombian"], answer: "Brazilian" },
    { question: "Which Grand Prix is held at Suzuka Circuit?", options: ["Japanese", "Chinese", "Korean", "Malaysian"], answer: "Japanese" },
    { question: "Which Grand Prix is held at Marina Bay?", options: ["Singapore", "Abu Dhabi", "Bahrain", "Qatar"], answer: "Singapore" },
    { question: "Which Grand Prix is held at Circuit de Catalunya?", options: ["Spanish", "Portuguese", "French", "Italian"], answer: "Spanish" },
    { question: "Which Grand Prix is held at Red Bull Ring?", options: ["Austrian", "German", "Swiss", "Hungarian"], answer: "Austrian" },
    { question: "Which Grand Prix is held at Hungaroring?", options: ["Hungarian", "Austrian", "Czech", "Polish"], answer: "Hungarian" },
    { question: "Which Grand Prix is held at Circuit Zandvoort?", options: ["Dutch", "Belgian", "German", "Luxembourg"], answer: "Dutch" },
    
    // Driver Transfers & Moves
    { question: "Which team did Fernando Alonso return to F1 with in 2021?", options: ["Alpine", "McLaren", "Ferrari", "Renault"], answer: "Alpine" },
    { question: "Which team did Sebastian Vettel join after leaving Red Bull?", options: ["Ferrari", "Mercedes", "McLaren", "Aston Martin"], answer: "Ferrari" },
    { question: "Which team did Daniel Ricciardo leave Red Bull for?", options: ["Renault", "McLaren", "Ferrari", "Mercedes"], answer: "Renault" },
    { question: "Which team did Carlos Sainz join in 2021?", options: ["Ferrari", "McLaren", "Renault", "Alpine"], answer: "Ferrari" },
    { question: "Who replaced Kimi Räikkönen at Alfa Romeo in 2022?", options: ["Valtteri Bottas", "Guanyu Zhou", "Antonio Giovinazzi", "Robert Kubica"], answer: "Valtteri Bottas" },
    { question: "Which team did Sergio Perez join in 2021?", options: ["Red Bull", "Racing Point", "McLaren", "Ferrari"], answer: "Red Bull" },
    { question: "Who did Sergio Perez replace at Red Bull?", options: ["Alexander Albon", "Pierre Gasly", "Daniel Ricciardo", "Max Verstappen"], answer: "Alexander Albon" },
    { question: "Which team did Pierre Gasly join in 2023?", options: ["Alpine", "AlphaTauri", "Red Bull", "McLaren"], answer: "Alpine" },
    { question: "Who replaced Pierre Gasly at AlphaTauri in 2023?", options: ["Nyck de Vries", "Liam Lawson", "Daniel Ricciardo", "Yuki Tsunoda"], answer: "Nyck de Vries" },
    { question: "Which team did Kevin Magnussen return to in 2022?", options: ["Haas", "Renault", "McLaren", "Racing Point"], answer: "Haas" },
    
    // Podiums & Wins
    { question: "Who has the most podium finishes in F1 history?", options: ["Lewis Hamilton", "Michael Schumacher", "Sebastian Vettel", "Fernando Alonso"], answer: "Lewis Hamilton" },
    { question: "Who was the last driver to win for Sauber/Alfa Romeo?", options: ["Robert Kubica (2008)", "Kimi Räikkönen", "Felipe Massa", "Nick Heidfeld"], answer: "Robert Kubica (2008)" },
    { question: "Who won the 2020 Sakhir GP for Racing Point?", options: ["Sergio Perez", "Lance Stroll", "Nico Hulkenberg", "Esteban Ocon"], answer: "Sergio Perez" },
    { question: "Who scored McLaren's first podium of the hybrid era?", options: ["Kevin Magnussen", "Jenson Button", "Fernando Alonso", "Stoffel Vandoorne"], answer: "Kevin Magnussen" },
    { question: "Who won the 2021 Hungarian GP after a chaotic start?", options: ["Esteban Ocon", "Sebastian Vettel", "Lewis Hamilton", "Carlos Sainz"], answer: "Esteban Ocon" },
    { question: "Who scored their first podium at the 2021 Russian GP?", options: ["Lando Norris", "Carlos Sainz", "George Russell", "Pierre Gasly"], answer: "Lando Norris" },
    { question: "Who won the 2022 Australian GP?", options: ["Charles Leclerc", "Max Verstappen", "Sergio Perez", "George Russell"], answer: "Charles Leclerc" },
    { question: "Who won the 2022 Singapore GP?", options: ["Sergio Perez", "Charles Leclerc", "Max Verstappen", "Carlos Sainz"], answer: "Sergio Perez" },
    { question: "Who scored their first F1 win at the 2023 Singapore GP?", options: ["Carlos Sainz", "Lando Norris", "George Russell", "Oscar Piastri"], answer: "Carlos Sainz" },
    { question: "How many races did Mercedes win in 2022?", options: ["1", "0", "2", "3"], answer: "1" },
    
    // Miscellaneous
    { question: "What is the official name of F1's governing body?", options: ["FIA", "FOM", "F1", "FISA"], answer: "FIA" },
    { question: "Who is the current F1 CEO?", options: ["Stefano Domenicali", "Chase Carey", "Bernie Ecclestone", "Jean Todt"], answer: "Stefano Domenicali" },
    { question: "What does FIA stand for?", options: ["Fédération Internationale de l'Automobile", "Formula International Association", "Federation of International Automobiles", "Formula Industry Association"], answer: "Fédération Internationale de l'Automobile" },
    { question: "Who was F1's long-time commercial boss until 2017?", options: ["Bernie Ecclestone", "Chase Carey", "Stefano Domenicali", "Max Mosley"], answer: "Bernie Ecclestone" },
    { question: "What is the name of F1's official tire supplier?", options: ["Pirelli", "Bridgestone", "Michelin", "Goodyear"], answer: "Pirelli" },
    { question: "What is the name of F1's official fuel supplier?", options: ["Varies by team", "Shell", "Petronas", "Mobil 1"], answer: "Varies by team" },
    { question: "What is the minimum driver weight in F1?", options: ["80 kg", "75 kg", "70 kg", "85 kg"], answer: "80 kg" },
    { question: "What is parc fermé?", options: ["Restricted area where cars can't be modified", "Pit lane", "Paddock area", "Media center"], answer: "Restricted area where cars can't be modified" },
    { question: "What does 'box box' mean in F1?", options: ["Pit stop instruction", "Overtake", "Slow down", "Push hard"], answer: "Pit stop instruction" },
    { question: "What is the 107% rule?", options: ["Qualifying time limit", "Race distance", "Pit stop time", "Fuel limit"], answer: "Qualifying time limit" },
    
    // 2024 Season Specific
    { question: "How many races were in the 2024 F1 calendar?", options: ["24", "23", "22", "25"], answer: "24" },
    { question: "Which team did Lewis Hamilton announce he's joining for 2025?", options: ["Ferrari", "Red Bull", "McLaren", "Aston Martin"], answer: "Ferrari" },
    { question: "Who replaced Nyck de Vries at AlphaTauri mid-2023?", options: ["Daniel Ricciardo", "Liam Lawson", "Yuki Tsunoda", "Nick Cassidy"], answer: "Daniel Ricciardo" },
    { question: "Which circuit returned to the calendar in 2023?", options: ["Qatar", "Turkey", "Malaysia", "India"], answer: "Qatar" },
    { question: "Which circuit was added to the 2023 calendar?", options: ["Las Vegas", "Kyalami", "Indianapolis", "Portimão"], answer: "Las Vegas" },
    { question: "What was the name of Red Bull's 2024 car?", options: ["RB20", "RB19", "RB21", "RB18"], answer: "RB20" },
    { question: "What was the name of Ferrari's 2024 car?", options: ["SF-24", "SF-23", "F1-75", "SF-21"], answer: "SF-24" },
    { question: "What was the name of Mercedes' 2024 car?", options: ["W15", "W14", "W16", "W13"], answer: "W15" },
    { question: "Which team changed their name from AlphaTauri?", options: ["RB (Racing Bulls)", "Toro Rosso", "Red Bull Junior", "Alpha Racing"], answer: "RB (Racing Bulls)" },
    { question: "Who was Sauber's title sponsor in 2024?", options: ["Stake", "Alfa Romeo", "BMW", "Petronas"], answer: "Stake" },
];
